import { COMPANY_NAME } from './pdfUtils'

export function drawFooter(pdf: any, pageNo: number, totalPages: number) {
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()

  pdf.setFillColor(7, 38, 75)
  pdf.rect(0, pageHeight - 17, pageWidth, 17, 'F')

  pdf.setTextColor(255)
  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(8)
  pdf.text(COMPANY_NAME, 12, pageHeight - 10)

  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(7)
  pdf.text('Generated by PGT Driver Trip System', 12, pageHeight - 5)

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(8)
  pdf.text(`Page ${pageNo} of ${totalPages}`, pageWidth - 12, pageHeight - 7, {
    align: 'right',
  })

  pdf.setTextColor(0)
}
